import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Topbar } from "@/components/layout/Topbar";
import CyberpunkBackground from "@/components/layout/DesktopBackground";
import Footer from "@/components/layout/Footer";
import { CyberToastContainer } from "@/components/toast/CyberToastContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen w-full flex flex-col bg-gray-900 overflow-hidden relative">
          <CyberpunkBackground />
          <Topbar />
          {children}
          <Footer />
          <CyberToastContainer />
        </div>
      </body>
    </html>
  );
}
